[package]
name = "canvas"
version = "0.1.0"
authors = ["Sebastian Köln <sebk@rynx.org>"]

[dependencies]
rand = "*"
num = "*"
prefetch = "*"
tuple = { version = "*", git = "https://github.com/s3bk/tuple.git" }
palette = "*"
lazy_static = "*"
math = { version = "*", git = "https://github.com/s3bk/math.git" }

[dependencies.image]
version = "0.14"
default-features = false
features = ["png_codec"]

[dev-dependencies]
fmath = { version = "*", git = "https://github.com/s3bk/fmath.git" }
simd = "*"
show = { git = "https://github.com/s3bk/show.git" }

[profile.release]
opt-level = 3
